services:
  - type: web
    name: sky-seeker-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js

  - type: static
    name: sky-seeker-frontend
    rootDir: frontend
    staticPublishPath: .
