services:
  - type: web
    name: sky-seeker-frontend
    env: static
    staticPublishPath: frontend
    buildCommand: ""
    branch: main

  - type: web
    name: sky-seeker-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    branch: main
    rootDir: backend
